"""rename department

Revision ID: 140c32797487
Revises: af2e03954f2a
Create Date: 2024-10-01 14:54:09.033558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140c32797487'
down_revision = 'af2e03954f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###